services:
    ambta_doctrine_encrypt.orm_subscriber:
        class: Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "@ambta_doctrine_encrypt.encryptor"]
        tags:
            -  { name: doctrine.event_subscriber }
    ambta_doctrine_encrypt.subscriber:
        alias: ambta_doctrine_encrypt.orm_subscriber
    ambta_doctrine_encrypt.encryptor:
        class: Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface
        factory: ['Ambta\DoctrineEncryptBundle\Encryptors\EncryptorFactory', create]
        arguments: ['%ambta_doctrine_encrypt.encryptor_class_name%']
    ambta_doctrine_encrypt.encryptor.encryptor_factory:
        class: Ambta\DoctrineEncryptBundle\Encryptors\EncryptorFactory
